#!/bin/sh
# Copyright 2016 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CHASSIS="$(mosys platform chassis)"
: "${CHASSIS:=LARS}"
echo "/etc/cras/${CHASSIS}"
