#!/bin/sh
# Copyright 2016 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CHASSIS="$(mosys platform chassis)"
: "${CHASSIS:=RELM}"

# Two special customization IDs were incorrectly assigned in wrong format that
# we have to white-list them.
CUSTOMIZATION_ID="$(vpd_get_value customization_id)"
case "${CUSTOMIZATION_ID}" in
  ACERTIFA | DASANI )
    CHASSIS="${CUSTOMIZATION_ID}"
    ;;
esac

echo "/etc/cras/${CHASSIS}"
