#!/bin/sh
# Copyright 2016 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

VPD_CACHE_FILE="/mnt/stateful_partition/unencrypted/cache/vpd/filtered.txt"
SERIES="RELM"
if [ -e "${VPD_CACHE_FILE}" ]; then
  CUSTOMIZATION_ID="$(sed -nre 's/^"customization_id"="(.+)"$/\1/p' \
                      <"${VPD_CACHE_FILE}")"
  if [ "${CUSTOMIZATION_ID}" = "ACERTIFA" ]; then
	SERIES="${CUSTOMIZATION_ID}"
  fi
fi
echo "/etc/cras/${SERIES}"
