#!/bin/bash
# Copyright 2016 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Do no collect any userland crash.
# Userland crash are reported in minidump format, which contains stack memory.
# Since COS do not depend on userland crashes for debugging (yet), we should
# remove it to simplify the privacy question.
exit 1
