#!/bin/sh

# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

. /usr/share/misc/chromeos-common.sh

# bootstat writes timings to both tmpfs and debugfs.
bootstat pre-startup

mount -o remount,noexec /dev/shm

# Prepare to mount stateful partition
ROOT_DEV=$(rootdev -s)
ROOTDEV_RET_CODE=$?
# Example root dev types we need to handle: /dev/sda2 -> /dev/sda,
# /dev/mmcblk0p0 -> /dev/mmcblk0p, /dev/ubi2_1 -> /dev/ubi
ROOTDEV_TYPE=$(echo $ROOT_DEV | sed 's/[0-9_]*$//')

# Load the GPT helper functions and the image settings.
. "/usr/sbin/write_gpt.sh"
load_base_vars

# Mount stateful partition
DIRTY_EXPIRE_CENTISECS=$(sysctl -n vm.dirty_expire_centisecs)
COMMIT_INTERVAL=$(( DIRTY_EXPIRE_CENTISECS / 100 ))
STATE_DEV=${ROOTDEV_TYPE}${PARTITION_NUM_STATE}
STATE_FLAGS="nodev,noexec,nosuid,commit=${COMMIT_INTERVAL}"

# Mount stateful partition from STATE_DEV.
mount -n -t ${FS_FORMAT_STATE} -o ${STATE_FLAGS} \
    "$STATE_DEV" /mnt/stateful_partition

# Make it a private mount so that mounts made inside /var and /home do not
# propagate here.
mount --make-private /mnt/stateful_partition

# Mount the OEM partition.
OEM_FLAGS="ro,nodev,noexec,nosuid"
OEM_DEV=${ROOTDEV_TYPE}${PARTITION_NUM_OEM}
mount -n -t ${FS_FORMAT_OEM} -o ${OEM_FLAGS} ${OEM_DEV} /usr/share/oem

bootstat post-startup
