#!/bin/bash
# Copyright 2015 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

ip6tables -P INPUT DROP -w
ip6tables -P FORWARD DROP -w
ip6tables -P OUTPUT DROP -w

# Accept everything on the loopback
ip6tables -I INPUT -i lo -j ACCEPT -w
ip6tables -I OUTPUT -o lo -j ACCEPT -w
