#!/bin/sh
# Copyright 2015 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

yes_or_no_prompt() {
  echo -n "$1 [y/N] "
  read answer
  case "${answer}" in
    [yY]*)
      echo "You answered YES"
      echo
      return 0
      ;;
    *)
      echo "You answered NO"
      echo
      return 1
      ;;
  esac
}

CHECK_FILE_PREFIX='.local_buildtools_skip_check_'
warn_check_failed() {
  local check_name="$1"
  local warning="$2"
  local check_file="${HOME}/${CHECK_FILE_PREFIX}${check_name}"

  if [ -e "${check_file}" ]; then
    return
  fi

  echo "${warning}"
  if yes_or_no_prompt "Do you want to skip this check in the future?"; then
    touch "${check_file}"
  fi
}

check_user_settings() {
  local warning

  if [ $(id -u) -eq 0 ]; then
    warning="
You seem to be running cbuildbot as root. This is not recommended.
Usually, you want to run this as the 'mobbuild' user.
"
    warn_check_failed "root_user" "${warning}"
  fi

  if [ ! -e "${HOME}/.gitcookies" ]; then
    warning="
We could not find a .gitcookies file at $HOME!
Perhaps you stashed it elsewhere?
"
    warn_check_failed "gitcookies" "${warning}"
  fi
  if [ ! -e "${HOME}/.netrc" ]; then
    warning="
We could not find a .netrc file at $HOME!
Perhaps you are using gitcookies?
"
    warn_check_failed "netrc" "${warning}"
  fi

  if ! git config --global --list 2>/dev/null | grep -q user.name ||
     ! git config --global --list 2>/dev/null | grep -q user.email; then
    warning="
Missing git settings.
Both user.name and user.email settings are required.
"
    warn_check_failed "git_config" "${warning}"
  fi
}

LOCAL_BUILDTOOLS_DIR=/b/local_buildtools
CBUILDBOT_PATH="${LOCAL_BUILDTOOLS_DIR}/chromiumos/chromite/bin/cbuildbot"
BOOTSTRAP_DIR="${LOCAL_BUILDTOOLS_DIR}/chromite_bootstrap"
if [ ! -f "${CBUILDBOT_PATH}" ]; then
  echo 'Local cbuildbot is not setup! Something went wrong during boot?' >&2
  exit 1
fi

# If cbuildbot is run in a setup without a bare minimum user configuration, it
# fails in very cryptic ways. This is very likely to happen on mobbuild systems.
# So, we sanity check before continuing.
check_user_settings

exec "${CBUILDBOT_PATH}" --local --bootstrap-dir "${BOOTSTRAP_DIR}" "$@"
