#!/bin/sh
# Copyright 2015 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CBUILDBOT_PATH=/b/local_buildtools/chromiumos/chromite/bin/cbuildbot
if [ ! -f "${CBUILDBOT_PATH}" ]; then
  echo 'Local cbuildbot is not setup! Something went wonky during boot?' >&2
  exit 1
fi

exec "${CBUILDBOT_PATH}" --local "$@"
