#!/bin/sh
# Copyright 2016 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

hw_version="$(mosys platform version)"

if [ "$hw_version" = "MP.A" ] ||
   [ "$hw_version" = "EVT" ] ||
   [ "$hw_version" = "DVT" ] ||
   [ "$hw_version" = "PVT" ]; then
    config_dir="pre_mp_a"
else
    config_dir="post_mp_a"
fi

echo "/etc/cras/${config_dir}"
