#!/bin/sh
# Copyright 2015 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

if ! mountpoint -q /etc; then
	ETC=/tmp/etc_overlay
	mkdir ${ETC}
	if mount -t tmpfs tmpfs ${ETC} -o size=1M,mode=755,nosuid,noexec,nodev ; then
		# Because /etc is read-only at the time systemd boots,
		# systemd saves machine-id in /run and then bind-mounts it
		# into /etc.  Below we unmount /etc/machine-id first and
		# then copy it from /run after /etc is remounted read-write.
		umount /etc/machine-id
		mkdir -p ${ETC}/etc ${ETC}/.work
		mount -o lowerdir=/etc,upperdir=${ETC}/etc,workdir=${ETC}/.work \
			-t overlay overlayfs /etc ||
			logger -t "$UPSTART_JOB" \
				"Cannot mount /etc overlay"
		umount ${ETC}
		rmdir ${ETC}
		cp /run/machine-id /etc/machine-id
	else
		logger -t "$UPSTART_JOB" "Cannot mount tmpfs at ${ETC}"
	fi
fi
